<?php

require_once __DIR__ . '/sponsor-logos.php';

$managedSponsorLogos = loadSponsorLogos(false);
$projectLogos = $managedSponsorLogos !== [] ? $managedSponsorLogos : defaultSponsorLogos();
$projectLogoCopy = $managedSponsorLogos !== []
    ? 'Sponsor logos uploaded through the CMS are shown below in the sliding carousel.'
    : 'Upload sponsor logos through the CMS to replace these temporary placeholders in the sliding carousel.';

$catalogueCategories = [
    [
        'id' => 'wayfinding-signs',
        'title' => 'Wayfinding Signs',
        'copy' => 'Directional signs for lobbies, tower cores, lift zones, parking decks, and shared circulation routes.',
        'highlights' => ['Lift lobbies and floor directories', 'Directional arrows and landmark markers', 'Consistent branding across multiple blocks'],
        'gallery' => [
            ['src' => 'assets/images/catalogue/wayfinding-signs/wayfinding-sign-01.jpg', 'alt' => 'Wayfinding sign sample 1'],
            ['src' => 'assets/images/catalogue/wayfinding-signs/wayfinding-sign-02.jpg', 'alt' => 'Wayfinding sign sample 2'],
            ['src' => 'assets/images/catalogue/wayfinding-signs/wayfinding-sign-03.jpg', 'alt' => 'Wayfinding sign sample 3'],
            ['src' => 'assets/images/catalogue/wayfinding-signs/wayfinding-sign-04.jpg', 'alt' => 'Wayfinding sign sample 4'],
            ['src' => 'assets/images/catalogue/wayfinding-signs/wayfinding-sign-05.jpg', 'alt' => 'Wayfinding sign sample 5'],
            ['src' => 'assets/images/catalogue/wayfinding-signs/wayfinding-sign-06.jpg', 'alt' => 'Wayfinding sign sample 6'],
            ['src' => 'assets/images/catalogue/wayfinding-signs/wayfinding-sign-07.jpg', 'alt' => 'Wayfinding sign sample 7'],
            ['src' => 'assets/images/catalogue/wayfinding-signs/wayfinding-sign-08.jpg', 'alt' => 'Wayfinding sign sample 8'],
        ],
    ],
    [
        'id' => 'notice-boards',
        'title' => 'Notice Boards',
        'copy' => 'Management notice boards and communication panels for announcements, circulars, and resident updates.',
        'highlights' => ['Indoor and semi-outdoor placements', 'Magnetic, acrylic, and lockable formats', 'Sized for management offices and common areas'],
        'gallery' => [
            ['src' => 'assets/images/catalogue/notice-boards/notice-board-01.jpg', 'alt' => 'Notice board sample 1'],
            ['src' => 'assets/images/catalogue/notice-boards/notice-board-02.jpg', 'alt' => 'Notice board sample 2'],
            ['src' => 'assets/images/catalogue/notice-boards/notice-board-03.jpg', 'alt' => 'Notice board sample 3'],
        ],
    ],
    [
        'id' => 'safety-warning-signs',
        'title' => 'Safety Warning Signs',
        'copy' => 'Mandatory, hazard, and warning signage designed to improve safety awareness in shared residential and commercial spaces.',
        'highlights' => ['Fire, electrical, and caution signage', 'Clear icon-driven communication', 'Durable finishes for high-traffic environments'],
        'gallery' => [
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-01.jpg', 'alt' => 'Safety warning sign sample 1'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-02.jpg', 'alt' => 'Safety warning sign sample 2'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-03.jpg', 'alt' => 'Safety warning sign sample 3'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-04.jpg', 'alt' => 'Safety warning sign sample 4'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-05.jpg', 'alt' => 'Safety warning sign sample 5'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-06.jpg', 'alt' => 'Safety warning sign sample 6'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-07.jpg', 'alt' => 'Safety warning sign sample 7'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-08.jpg', 'alt' => 'Safety warning sign sample 8'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-09.jpg', 'alt' => 'Safety warning sign sample 9'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-10.jpg', 'alt' => 'Safety warning sign sample 10'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-11.jpg', 'alt' => 'Safety warning sign sample 11'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-12.jpg', 'alt' => 'Safety warning sign sample 12'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-13.jpg', 'alt' => 'Safety warning sign sample 13'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-14.jpg', 'alt' => 'Safety warning sign sample 14'],
            ['src' => 'assets/images/catalogue/safety-warning-signs/safety-warning-sign-15.jpg', 'alt' => 'Safety warning sign sample 15'],
        ],
    ],
    [
        'id' => 'condominium-indoor-signage',
        'title' => 'Condominium Indoor Signage',
        'copy' => 'Interior signage systems including LED displays and 3D lettering for reception areas, corridors, and amenities.',
        'highlights' => ['LED feature signage', '3D lettering and branded wall signage', 'Lift lobby, corridor, and facility identification'],
        'gallery' => [
            ['src' => 'assets/images/catalogue/condominium-indoor-signage/condominium-indoor-signage-01.jpg', 'alt' => 'Condominium indoor signage sample 1'],
            ['src' => 'assets/images/catalogue/condominium-indoor-signage/condominium-indoor-signage-02.jpg', 'alt' => 'Condominium indoor signage sample 2'],
            ['src' => 'assets/images/catalogue/condominium-indoor-signage/condominium-indoor-signage-03.jpg', 'alt' => 'Condominium indoor signage sample 3'],
            ['src' => 'assets/images/catalogue/condominium-indoor-signage/condominium-indoor-signage-04.jpg', 'alt' => 'Condominium indoor signage sample 4'],
            ['src' => 'assets/images/catalogue/condominium-indoor-signage/condominium-indoor-signage-05.jpg', 'alt' => 'Condominium indoor signage sample 5'],
            ['src' => 'assets/images/catalogue/condominium-indoor-signage/condominium-indoor-signage-06.jpg', 'alt' => 'Condominium indoor signage sample 6'],
            ['src' => 'assets/images/catalogue/condominium-indoor-signage/condominium-indoor-signage-07.jpg', 'alt' => 'Condominium indoor signage sample 7'],
            ['src' => 'assets/images/catalogue/condominium-indoor-signage/condominium-indoor-signage-08.jpg', 'alt' => 'Condominium indoor signage sample 8'],
            ['src' => 'assets/images/catalogue/condominium-indoor-signage/condominium-indoor-signage-09.jpg', 'alt' => 'Condominium indoor signage sample 9'],
            ['src' => 'assets/images/catalogue/condominium-indoor-signage/condominium-indoor-signage-10.jpg', 'alt' => 'Condominium indoor signage sample 10'],
            ['src' => 'assets/images/catalogue/condominium-indoor-signage/condominium-indoor-signage-11.jpg', 'alt' => 'Condominium indoor signage sample 11'],
        ],
    ],
    [
        'id' => 'condominium-outdoor-signage',
        'title' => 'Condominium Outdoor Signage',
        'copy' => 'Exterior signage solutions such as frontlit, backlit, and lightbox systems engineered for visibility and weather exposure.',
        'highlights' => ['Main entrance branding', 'Frontlit, backlit, and lightbox fabrication', 'Built for outdoor visibility and maintenance access'],
        'gallery' => [
            ['src' => 'assets/images/catalogue/condominium-outdoor-signage/condominium-outdoor-signage-01.jpg', 'alt' => 'Condominium outdoor signage sample 1'],
            ['src' => 'assets/images/catalogue/condominium-outdoor-signage/condominium-outdoor-signage-02.jpg', 'alt' => 'Condominium outdoor signage sample 2'],
            ['src' => 'assets/images/catalogue/condominium-outdoor-signage/condominium-outdoor-signage-03.jpg', 'alt' => 'Condominium outdoor signage sample 3'],
            ['src' => 'assets/images/catalogue/condominium-outdoor-signage/condominium-outdoor-signage-04.jpg', 'alt' => 'Condominium outdoor signage sample 4'],
            ['src' => 'assets/images/catalogue/condominium-outdoor-signage/condominium-outdoor-signage-05.jpg', 'alt' => 'Condominium outdoor signage sample 5'],
            ['src' => 'assets/images/catalogue/condominium-outdoor-signage/condominium-outdoor-signage-06.jpg', 'alt' => 'Condominium outdoor signage sample 6'],
            ['src' => 'assets/images/catalogue/condominium-outdoor-signage/condominium-outdoor-signage-07.jpg', 'alt' => 'Condominium outdoor signage sample 7'],
            ['src' => 'assets/images/catalogue/condominium-outdoor-signage/condominium-outdoor-signage-08.jpg', 'alt' => 'Condominium outdoor signage sample 8'],
            ['src' => 'assets/images/catalogue/condominium-outdoor-signage/condominium-outdoor-signage-09.jpg', 'alt' => 'Condominium outdoor signage sample 9'],
            ['src' => 'assets/images/catalogue/condominium-outdoor-signage/condominium-outdoor-signage-10.jpg', 'alt' => 'Condominium outdoor signage sample 10'],
        ],
    ],
    [
        'id' => 'custom-number-signage',
        'title' => 'Custom Number Signage',
        'copy' => 'Unit numbers, block identifiers, and customized numbering systems for clear property identification.',
        'highlights' => ['Unit doors and parcel room labels', 'Block, floor, and bay numbering', 'Styles aligned with property branding'],
        'gallery' => [
            ['src' => 'assets/images/catalogue/custom-number-signage/custom-number-signage-01.jpg', 'alt' => 'Custom number signage sample 1'],
            ['src' => 'assets/images/catalogue/custom-number-signage/custom-number-signage-02.jpg', 'alt' => 'Custom number signage sample 2'],
            ['src' => 'assets/images/catalogue/custom-number-signage/custom-number-signage-03.jpg', 'alt' => 'Custom number signage sample 3'],
            ['src' => 'assets/images/catalogue/custom-number-signage/custom-number-signage-04.jpg', 'alt' => 'Custom number signage sample 4'],
            ['src' => 'assets/images/catalogue/custom-number-signage/custom-number-signage-05.jpg', 'alt' => 'Custom number signage sample 5'],
        ],
    ],
    [
        'id' => 'carpark-signage',
        'title' => 'Carpark Signage',
        'copy' => 'Traffic and parking signage that improves flow, safety, and level recognition throughout basement and podium parking areas.',
        'highlights' => ['Entry, exit, and directional markers', 'Reserved lot and level identification', 'Painted, mounted, and suspended options'],
        'gallery' => [
            ['src' => 'assets/images/catalogue/carpark-signage/carpark-signage-01.jpg', 'alt' => 'Carpark signage sample 1'],
            ['src' => 'assets/images/catalogue/carpark-signage/carpark-signage-02.jpg', 'alt' => 'Carpark signage sample 2'],
            ['src' => 'assets/images/catalogue/carpark-signage/carpark-signage-03.jpg', 'alt' => 'Carpark signage sample 3'],
            ['src' => 'assets/images/catalogue/carpark-signage/carpark-signage-04.jpg', 'alt' => 'Carpark signage sample 4'],
            ['src' => 'assets/images/catalogue/carpark-signage/carpark-signage-05.jpeg', 'alt' => 'Carpark signage sample 5'],
            ['src' => 'assets/images/catalogue/carpark-signage/carpark-signage-06.jpg', 'alt' => 'Carpark signage sample 6'],
            ['src' => 'assets/images/catalogue/carpark-signage/carpark-signage-07.jpg', 'alt' => 'Carpark signage sample 7'],
            ['src' => 'assets/images/catalogue/carpark-signage/carpark-signage-08.jpg', 'alt' => 'Carpark signage sample 8'],
            ['src' => 'assets/images/catalogue/carpark-signage/carpark-signage-09.jpg', 'alt' => 'Carpark signage sample 9'],
            ['src' => 'assets/images/catalogue/carpark-signage/carpark-signage-10.jpg', 'alt' => 'Carpark signage sample 10'],
            ['src' => 'assets/images/catalogue/carpark-signage/carpark-signage-11.jpg', 'alt' => 'Carpark signage sample 11'],
        ],
    ],
    [
        'id' => 'advertising-signage',
        'title' => 'Advertising Signage',
        'copy' => 'Promotional and branding displays for campaigns, launches, and shared-property marketing placements.',
        'highlights' => ['Promotional display panels', 'Short-term and long-term campaign formats', 'Suitable for foyers, event zones, and storefronts'],
        'gallery' => [
            ['src' => 'assets/images/catalogue/advertising-signage/advertising-signage-01.jpg', 'alt' => 'Advertising signage sample 1'],
            ['src' => 'assets/images/catalogue/advertising-signage/advertising-signage-02.jpg', 'alt' => 'Advertising signage sample 2'],
            ['src' => 'assets/images/catalogue/advertising-signage/advertising-signage-03.jpg', 'alt' => 'Advertising signage sample 3'],
            ['src' => 'assets/images/catalogue/advertising-signage/advertising-signage-04.jpg', 'alt' => 'Advertising signage sample 4'],
            ['src' => 'assets/images/catalogue/advertising-signage/advertising-signage-05.jpg', 'alt' => 'Advertising signage sample 5'],
            ['src' => 'assets/images/catalogue/advertising-signage/advertising-signage-06.jpg', 'alt' => 'Advertising signage sample 6'],
            ['src' => 'assets/images/catalogue/advertising-signage/advertising-signage-07.jpg', 'alt' => 'Advertising signage sample 7'],
            ['src' => 'assets/images/catalogue/advertising-signage/advertising-signage-08.jpg', 'alt' => 'Advertising signage sample 8'],
            ['src' => 'assets/images/catalogue/advertising-signage/advertising-signage-09.jpg', 'alt' => 'Advertising signage sample 9'],
        ],
    ],
    [
        'id' => 'door-signage',
        'title' => 'Door Signage',
        'copy' => 'Door signs and room identifiers that make office, utility, and facility access clearer for residents and visitors.',
        'highlights' => ['Office, service room, and utility labels', 'Readable at close range and corridor distance', 'Available in engraved, acrylic, and metal finishes'],
        'gallery' => [
            ['src' => 'assets/images/catalogue/door-signage/door-signage-01.jpg', 'alt' => 'Door signage sample 1'],
            ['src' => 'assets/images/catalogue/door-signage/door-signage-02.jpg', 'alt' => 'Door signage sample 2'],
            ['src' => 'assets/images/catalogue/door-signage/door-signage-03.jpg', 'alt' => 'Door signage sample 3'],
            ['src' => 'assets/images/catalogue/door-signage/door-signage-04.jpg', 'alt' => 'Door signage sample 4'],
            ['src' => 'assets/images/catalogue/door-signage/door-signage-05.jpg', 'alt' => 'Door signage sample 5'],
            ['src' => 'assets/images/catalogue/door-signage/door-signage-06.jpg', 'alt' => 'Door signage sample 6'],
            ['src' => 'assets/images/catalogue/door-signage/door-signage-07.jpg', 'alt' => 'Door signage sample 7'],
        ],
    ],
    [
        'id' => 'amenity-signage',
        'title' => 'Amenity Signage',
        'copy' => 'Facility markers and rules signage for gyms, pools, halls, lounges, and other shared amenity areas.',
        'highlights' => ['Amenity naming and rule boards', 'Designed to match shared-space interiors', 'Supports better guest and resident navigation'],
        'gallery' => [
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-01.jpg', 'alt' => 'Amenity signage sample 1'],
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-02.jpg', 'alt' => 'Amenity signage sample 2'],
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-03.jpg', 'alt' => 'Amenity signage sample 3'],
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-04.jpg', 'alt' => 'Amenity signage sample 4'],
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-05.jpg', 'alt' => 'Amenity signage sample 5'],
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-06.jpg', 'alt' => 'Amenity signage sample 6'],
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-07.jpg', 'alt' => 'Amenity signage sample 7'],
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-08.jpg', 'alt' => 'Amenity signage sample 8'],
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-09.jpg', 'alt' => 'Amenity signage sample 9'],
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-10.jpg', 'alt' => 'Amenity signage sample 10'],
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-11.jpg', 'alt' => 'Amenity signage sample 11'],
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-12.jpg', 'alt' => 'Amenity signage sample 12'],
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-13.jpg', 'alt' => 'Amenity signage sample 13'],
            ['src' => 'assets/images/catalogue/amenity-signage/amenity-signage-14.jpg', 'alt' => 'Amenity signage sample 14'],
        ],
    ],
];

$siteConfig = [
    'brand' => [
        'name' => 'Condo Signage',
        'company' => 'A&T Media Sdn. Bhd.',
        'tagline' => 'Professional condominium and commercial signage solutions.',
        'logo' => 'logo.jpg',
        'website' => 'www.antsignage.com',
    ],
    'meta' => [
        'title' => 'Condo Signage | Professional Signage Solutions',
        'description' => 'Condo Signage delivers professional signage solutions for condominiums and commercial properties, from design and fabrication to installation.',
    ],
    'nav' => [
        ['key' => 'home', 'label' => 'Home', 'href' => '#home'],
        ['key' => 'about', 'label' => 'About Us', 'href' => '#about'],
        ['key' => 'catalogue', 'label' => 'Product Catalogue', 'href' => '#products'],
        ['key' => 'contact', 'label' => 'Contact Us', 'href' => '#contact'],
        ['key' => 'projects', 'label' => 'Projects', 'href' => '#projects'],
        ['key' => 'services', 'label' => 'Services', 'href' => '#services'],
    ],
    'heroSlides' => [
        [
            'className' => 'slide-one',
            'tag' => 'Professional Signage Solutions',
            'title' => 'Clear, durable signage designed for condominium environments.',
            'titleTag' => 'h1',
            'copy' => 'Condo Signage helps property managers and developers present a polished building identity with compliant, durable, and management-approved signage systems.',
            'actions' => [
                ['label' => 'Explore Products', 'href' => 'catalogue.php', 'className' => 'btn btn-brand btn-lg'],
                ['label' => 'Learn More', 'href' => '#about', 'className' => 'btn btn-outline-light btn-lg'],
            ],
            'panel' => [
                'title' => 'Built for modern properties',
                'copy' => 'Wayfinding, safety signage, notice boards, amenity signs, and custom solutions produced with consistent branding and reliable materials.',
            ],
        ],
        [
            'className' => 'slide-two',
            'tag' => 'From Assessment To Installation',
            'title' => 'One team handling planning, fabrication, and on-site execution.',
            'titleTag' => 'h2',
            'copy' => 'We support each stage of the signage process, from site assessment and design mockups to fabrication and professional installation.',
            'metrics' => [
                ['number' => '01', 'label' => 'Site Assessment'],
                ['number' => '02', 'label' => 'Design Mockup'],
                ['number' => '03', 'label' => 'Installation'],
            ],
        ],
        [
            'className' => 'slide-three',
            'tag' => 'Trusted Product Range',
            'title' => 'Indoor and outdoor signage tailored to residential and commercial settings.',
            'titleTag' => 'h2',
            'copy' => 'Our product range covers notice boards, safety warning signs, door signage, car park signage, number plates, and custom branding displays.',
            'actions' => [
                ['label' => 'Talk To Our Team', 'href' => '#contact', 'className' => 'btn btn-brand btn-lg mt-3'],
            ],
        ],
    ],
    'about' => [
        'tag' => 'About Us',
        'title' => 'Reliable signage support for property management teams.',
        'image' => [
            'src' => 'assets/images/photo-team.png',
            'alt' => 'A&T Media team photo',
            'caption' => 'Our team combines production, design, installation, and quality control experience under one roof.',
        ],
        'paragraphs' => [
            'A&T Media Sdn. Bhd. is a printing and advertising company that provides signage design and creation in the Kuala Lumpur (KL) area. Our headquarters is situated at Ulu Tiram, Johor, Malaysia.',
            'We provide a variety of in-house support in production, design, marketing, on-site installation, and evaluation.',
            'Each product is produced by our experienced production team and quality checked by our senior production manager, who has 20 years of experience.',
            'Not only do we have a strong team, but we also have 10,000 square feet of production space and state-of-the-art equipment such as routers, lasers, UV printers, plotters, cutting beds, 3D lettering machines, and automatic welding machines.',
        ],
    ],
    'sections' => [
        'products' => [
            'tag' => 'Products',
            'title' => 'Signage categories for every key touchpoint.',
            'copy' => 'Our product range is structured to support navigation, safety, communication, and brand presentation across the entire property.',
            'items' => array_map(
                static fn(array $category): array => [
                    'title' => $category['title'],
                    'copy' => $category['copy'],
                    'href' => 'catalogue.php#' . $category['id'],
                ],
                $catalogueCategories
            ),
        ],
        'projects' => [
            'tag' => 'Projects',
            'title' => 'Companies that have used our services.',
            'copy' => $projectLogoCopy,
            'logos' => $projectLogos,
        ],
        'reviews' => [
            'tag' => 'Google Reviews',
            'title' => 'Public feedback from our Google profile.',
            'copy' => 'A selection of verified 5-star Google reviews from clients who engaged A&T for signboard design, fabrication, and installation.',
            'summary' => [
                'rating' => '5.0',
                'countLabel' => '28 Google reviews',
                'ctaLabel' => 'View On Google',
                'ctaHref' => 'https://maps.app.goo.gl/WsecQHUZpM75S1mu8',
            ],
            'items' => [
                [
                    'author' => 'Admin',
                    'meta' => '3 reviews · 4 photos · 5 months ago',
                    'rating' => 5,
                    'copy' => 'Very impressed with A&T Signboard! The designer is professional and helpful, giving great design options that fit customer needs. Really satisfied with the final artwork!!',
                ],
                [
                    'author' => 'Crudites Events',
                    'meta' => '1 review · 2 months ago',
                    'rating' => 5,
                    'copy' => 'Excellent service team, managed to provide advice and suggestions on signboard design and installation. Very much recommended!',
                ],
                [
                    'author' => 'Ghost Me',
                    'meta' => '5 reviews · 4 photos · 5 months ago',
                    'rating' => 5,
                    'copy' => 'A&T Signboard team is awesome! Easy to talk and their artwork is so nice. Really satisfied with the result!',
                ],
                [
                    'author' => 'Li Anne',
                    'meta' => '12 reviews · 4 photos · 2 months ago',
                    'rating' => 5,
                    'copy' => 'Very good service and excellent quality signboard. Highly recommended!!',
                ],
                [
                    'author' => 'Ivan "Iv.A" Ang',
                    'meta' => '5 reviews · 5 months ago',
                    'rating' => 5,
                    'copy' => 'Friendly and professional team, recommended for advertising needs and wants. Good job and keep it up!',
                ],
                [
                    'author' => 'Ehsan Property',
                    'meta' => '1 review · 1 photo · a year ago',
                    'rating' => 5,
                    'copy' => 'We had a great experience dealing with Mr. Ray Tan and his team. We ordered a signboard, and they provided excellent service. The font and overall design were neat and beautiful. This is the second time we have ordered from this company, and I highly recommend them for their outstanding customer care and top-notch service!',
                ],
                [
                    'author' => 'Jessyca Yong',
                    'meta' => 'Local Guide · 41 reviews · 6 photos · a year ago',
                    'rating' => 5,
                    'copy' => 'Highly recommend! very responsive and reasonable pricing. Thanks Brandon for his good service. hope to collaborate more on highway projects.',
                ],
                [
                    'author' => 'SoftiexDinox',
                    'meta' => 'Local Guide · 17 reviews · 8 photos · 5 months ago',
                    'rating' => 5,
                    'copy' => 'A&T Advertising PTE LTD. Very nice and professional service!',
                ],
                [
                    'author' => 'Owen Lee',
                    'meta' => 'Local Guide · 8 reviews · 6 photos · 7 months ago',
                    'rating' => 5,
                    'copy' => 'Superb service and quality signage from A&T Advertising.',
                ],
                [
                    'author' => 'Y S Chang',
                    'meta' => '4 reviews · 5 months ago',
                    'rating' => 5,
                    'copy' => 'Excellent quality product with service.',
                ],
                [
                    'author' => 'Wan Brandon',
                    'meta' => '4 reviews · 1 photo · a year ago',
                    'rating' => 5,
                    'copy' => 'Professional signboard maker in Klang Valley. Reasonable price, and quality product and service. Must choose A&T.',
                ],
                [
                    'author' => 'Naqiah',
                    'meta' => '3 reviews · 1 photo · 5 months ago',
                    'rating' => 5,
                    'copy' => 'Good service and quality in signboard.',
                ],
                [
                    'author' => 'My Love',
                    'meta' => '1 review · 2 months ago',
                    'rating' => 5,
                    'copy' => 'Good service.',
                ],
                [
                    'author' => 'zy tan',
                    'meta' => '4 reviews · 1 photo · 8 months ago',
                    'rating' => 5,
                    'copy' => 'SY Printing good service.',
                ],
                [
                    'author' => 'Vennibell',
                    'meta' => '1 review · 5 months ago',
                    'rating' => 5,
                    'copy' => 'Very good!',
                ],
                [
                    'author' => 'R4Rei Tan (R4Rei)',
                    'meta' => '11 reviews · 2 years ago',
                    'rating' => 5,
                    'copy' => 'Good services.',
                ],
                [
                    'author' => 'Hashim Abdullah',
                    'meta' => '7 reviews · 8 photos · a year ago',
                    'rating' => 5,
                    'copy' => 'It is a pleasure to deal with A & T. All questions and suggestions received good cooperation and response.',
                ],
                [
                    'author' => 'shimin Tan',
                    'meta' => '4 reviews · 2 photos · 5 months ago',
                    'rating' => 5,
                    'copy' => 'The new sign is really nice! The workmanship is very fine, and when the light is on it looks very textured.',
                ],
                [
                    'author' => 'Fariq hakimi',
                    'meta' => '2 reviews · 3 photos · 5 months ago',
                    'rating' => 5,
                    'copy' => 'Very good work.',
                ],
                [
                    'author' => 'Nur Milah',
                    'meta' => '5 months ago',
                    'rating' => 5,
                    'copy' => '5-star Google review.',
                ],
                [
                    'author' => 'Babuwilna Wilnasani',
                    'meta' => '5 months ago',
                    'rating' => 5,
                    'copy' => '5-star Google review.',
                ],
                [
                    'author' => 'Syafawani Mukayat',
                    'meta' => '1 review · 2 photos · 5 months ago',
                    'rating' => 5,
                    'copy' => '5-star Google review.',
                ],
                [
                    'author' => 'Eugene Loo',
                    'meta' => '2 reviews · 2 photos · 5 months ago',
                    'rating' => 5,
                    'copy' => '5-star Google review.',
                ],
                [
                    'author' => 'Mohd Faizal Faizaliyananas',
                    'meta' => '1 review · 5 months ago',
                    'rating' => 5,
                    'copy' => '5-star Google review.',
                ],
                [
                    'author' => 'Shinee Pong',
                    'meta' => 'Local Guide · 17 reviews · 226 photos · a year ago',
                    'rating' => 5,
                    'copy' => '5-star Google review.',
                ],
                [
                    'author' => 'JIA SHENG CHIN',
                    'meta' => '4 reviews · 2 photos · a year ago',
                    'rating' => 5,
                    'copy' => '5-star Google review.',
                ],
                [
                    'author' => 'Chloe Tan',
                    'meta' => '1 review · 2 years ago',
                    'rating' => 5,
                    'copy' => '5-star Google review.',
                ],
                [
                    'author' => 'Rei Tan',
                    'meta' => '2 years ago',
                    'rating' => 5,
                    'copy' => '5-star Google review.',
                ],
            ],
        ],
    ],
    'catalogue' => [
        'tag' => 'Product Catalogue',
        'title' => 'Signage categories arranged for condominium operations.',
        'copy' => 'Browse the full catalogue by category and jump directly to the signage systems your property needs.',
        'intro' => 'This page groups our condominium signage solutions into practical categories so management teams can review scope, function, and likely applications faster.',
        'categories' => $catalogueCategories,
    ],
    'services' => [
        'tag' => 'Services',
        'eyebrow' => 'Our Process',
        'title' => 'Structured & Management-Friendly',
        'copy' => 'Minimal disruption. Clear communication. Reliable delivery.',
        'steps' => [
            ['number' => '01', 'title' => 'Site Assessment', 'copy' => 'Visibility, layout & requirements'],
            ['number' => '02', 'title' => 'Design Mockup', 'copy' => 'Placement visuals for review & approval'],
            ['number' => '03', 'title' => 'Fabrication', 'copy' => 'Quality materials & workmanship'],
            ['number' => '04', 'title' => 'Installation', 'copy' => 'Safe, neat & coordinated execution'],
        ],
        'highlights' => [
            'Clear layout and placement planning for approvals',
            'Durable materials suitable for Malaysia\'s climate',
            'Professional appearance that enhances property value',
            'Experience working in occupied and managed buildings',
            'Smooth coordination with management and site teams',
            'Designed with long-term maintenance and visibility in mind.',
        ],
        'ctaTitle' => 'Looking for a Reliable Signage Partner?',
        'ctaCopy' => 'Whether it\'s a new development, signage replacement, or building upgrade, we provide solutions you can approve with confidence.',
        'ctaLinkLabel' => 'Contact us for a free consultation or site assessment.',
        'ctaLinkHref' => '#contact',
    ],
    'contact' => [
        'tag' => 'Contact Us',
        'title' => 'Reach Our Team',
        'copy' => 'Get in touch with our headquarters team for enquiries, quotation requests, and project discussions.',
        'branches' => [
            [
                'id' => 'branch',
                'label' => 'Branch',
                'active' => false,
                'office' => [
                    'name' => 'A&T Media Branch Office',
                    'registration' => 'Malaysia branch enquiries are coordinated through our central team.',
                    'addressLines' => [
                        'Branch visits are available by appointment for project coordination,',
                        'site review planning, and installation support.',
                    ],
                ],
                'contactBlocks' => [
                    ['label' => 'Contact No', 'value' => '+60164399639'],
                    ['label' => 'Email Address', 'value' => 'antadv.rei@gmail.com'],
                ],
                'quickActions' => [
                    'phone' => ['label' => 'Call Us', 'value' => '+60164399639', 'href' => 'tel:+60164399639'],
                    'email' => ['label' => 'Email Us', 'value' => 'antadv.rei@gmail.com', 'href' => 'mailto:antadv.rei@gmail.com'],
                ],
                'whatsApp' => [
                    'label' => 'WhatsApp Us',
                    'subLabel' => 'Click to chat',
                    'href' => 'https://wa.me/60164399639',
                ],
            ],
            [
                'id' => 'hq',
                'label' => 'HQ',
                'active' => true,
                'office' => [
                    'name' => 'A&T Media Sdn. Bhd.',
                    'registration' => '202501057902 (1659308-W)',
                    'addressLines' => [
                        '16, Jalan Nilam 1/6, Taman Teknologi Tinggi Subang,',
                        '47500 Subang Jaya, Selangor, Malaysia.',
                    ],
                ],
                'contactBlocks' => [
                    ['label' => 'Contact No', 'value' => '+60164399639'],
                    ['label' => 'Email Address', 'value' => 'antadv.rei@gmail.com'],
                ],
                'quickActions' => [
                    'phone' => ['label' => 'Call Us', 'value' => '+60164399639', 'href' => 'tel:+60164399639'],
                    'email' => ['label' => 'Email Us', 'value' => 'antadv.rei@gmail.com', 'href' => 'mailto:antadv.rei@gmail.com'],
                ],
                'whatsApp' => [
                    'label' => 'WhatsApp Us',
                    'subLabel' => 'Click to chat',
                    'href' => 'https://wa.me/60164399639',
                ],
            ],
            [
                'id' => 'branch-sg',
                'label' => 'Branch SG',
                'active' => false,
                'office' => [
                    'name' => 'A&T Media Singapore Branch',
                    'registration' => 'Singapore branch enquiries can be routed through our regional team.',
                    'addressLines' => [
                        'Please contact us to arrange Singapore project discussions,',
                        'quotation review, and cross-border signage coordination.',
                    ],
                ],
                'contactBlocks' => [
                    ['label' => 'Contact No', 'value' => '+60164399639'],
                    ['label' => 'Email Address', 'value' => 'antadv.rei@gmail.com'],
                ],
                'quickActions' => [
                    'phone' => ['label' => 'Call Us', 'value' => '+60164399639', 'href' => 'tel:+60164399639'],
                    'email' => ['label' => 'Email Us', 'value' => 'antadv.rei@gmail.com', 'href' => 'mailto:antadv.rei@gmail.com'],
                ],
                'whatsApp' => [
                    'label' => 'WhatsApp Us',
                    'subLabel' => 'Click to chat',
                    'href' => 'https://wa.me/60164399639',
                ],
            ],
        ],
        'formFields' => [
            ['id' => 'name', 'label' => 'Name*', 'type' => 'text', 'placeholder' => 'Enter name here', 'columnClass' => 'col-12'],
            ['id' => 'phone', 'label' => 'Contact Number*', 'type' => 'tel', 'placeholder' => 'Enter contact number here', 'columnClass' => 'col-md-7'],
            ['id' => 'email', 'label' => 'Email*', 'type' => 'email', 'placeholder' => 'Enter email address here', 'columnClass' => 'col-md-5'],
            ['id' => 'attachment', 'label' => 'Upload File (optional)', 'type' => 'file', 'columnClass' => 'col-12'],
            ['id' => 'message', 'label' => 'Message (optional)', 'type' => 'textarea', 'placeholder' => 'Enter message here', 'columnClass' => 'col-12', 'rows' => 5],
        ],
        'submitLabel' => 'Send Inquiry',
    ],
];